### ISSUE TITLE
Feature request: Copy individual file to different filename

### ISSUE THREAD

**Issue by jrmyio** [LinbuduLab/esbuild-plugins#68]
I am trying to move from `webpack-copy-plugin` to `esbuild-plugin-copy`.

However one of the things that currently doesn't seem supported is copying a file from for example `hello.txt` to `world.txt`. It instead creates a `world.txt` directory.

**Comment by linbudu599** [comment]
This is supported in latest version `1.0.1` now.

**Comment by jrmyio** [comment]
It seems that when I specify a `resolveFrom` to an absolute dir, something like:
    {
         ....
        to: './test.js',
    },
Still tries to make a folder `test.js`. This seems to be no the case when you use `out` or `cwd` as `resolveFrom`.

**Comment by linbudu599** [comment]
This was fixed now in `1.2.1`, which is indeed a mistake.

Also, option `resolveFrom ` is not actually designed to solve the file naming problem, but to control the destination resolve, I used another separate piece of code logic to solve the independent file naming problem.

A new option `dryRun` was introduced to avoid unexpected cases which may make your project folders a mess.

**Comment by jrmyio** [comment]
After upgrading from 1.3 to the new version, trying to copy a single filename to a different filename again creates a directory rather than a file.

**Comment by linbudu599** [comment]
Should got fixed in `2.0.2` now.
