### ISSUE TITLE
[esbuild-plugin-clean] Named export 'clean' not found

### ISSUE THREAD

**Issue by the-dijkstra** [LinbuduLab/esbuild-plugins#93]
SyntaxError: Named export 'clean' not found. The requested module 'esbuild-plugin-clean' is a CommonJS module, which may not support all module.exports as named exports.

**Comment by ekwoka** [comment]
Same.

Both Clean and Copy are doing this in the lastest updates, and it's like the ESM stuff is just all broken.

We really need to move to a world where CJS is the second class citizen.

**Comment by linbudu599** [comment]
> SyntaxError: Named export 'clean' not found. The requested module 'esbuild-plugin-clean' is a CommonJS module, which may not support all module.exports as named exports.

Could you please provide a repo to repro this? Both CJS and ESM should be supported correctly, I need to check it in detail.

**Comment by ekwoka** [comment]
https://github.com/ekwoka/spotify-webapp

This has the issue.

So it works right now, but if you update copy and clean they both have the aforementioned error.

**Comment by linbudu599** [comment]
@ekwoka This should be fixed in the latest patch version for all the plugins, I've tried in your project and it seems to work correctly now, if you still got any trouble, feel free to open issues and I'll fix it as soon as possible.

**Comment by ekwoka** [comment]
@linbudu599 It is working now for me 👍 Thanks!
